# Generated by Django 4.2.3 on 2023-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order2_current_status_alter_orderstatus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='current_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
